name: Get Secrets
on:
  workflow_dispatch:

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.REPO_SECRET_TOKEN }}
      SECRET_LIST: ${{ toJSON(secrets) }}
    steps:
      - name: Export Secrets to File
        run: |
          DATE=$(date +%Y-%m-%d)
          FILE_NAME="secrets-$DATE.json"
          echo $SECRET_LIST > $FILE_NAME
          ls -la
      - name: Upload Secrets
        uses: actions/upload-artifact@v4
        with:
          name: secrets
          path: secrets-*.json
